language: android
dist: precise
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - android-23
    - sys-img-armeabi-v7a-android-21


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-c81a61d9'
    - 'google-gdk-license-9529f459'
    - 'android-sdk-license-5be876d5'
    - 'android-sdk-license-2742d1c5'
    #- 'android-sdk-preview-license-.+'
    #- 'android-sdk-license-.+'
    #- 'google-gdk-license-.+'

before_script:
  - android update sdk --no-ui --filter build-tools-24.0.1,android-24,extra-android-m2repository
  - android list targets
  - echo no | android create avd --force -n test -t android-10 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck