language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22
    - extra-google-google_play_services

licenses:
    - 'android-sdk-preview-license-.+'
    - echo y
    - 'android-sdk-license-.+'
    - echo y
    - 'google-gdk-license-.+'
    - echo y

before_script:
  - android update sdk --no-ui --filter build-tools-24.0.1,android-24,extra-android-m2repository
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck